### ISSUE TITLE
error

### ISSUE THREAD

**Issue by farenhite** [ozkc/instagram-unfollowers#2]
F:\py>py -2.7 main.py 528817151
 ~ Connecting to Instagram
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    if insta.login() == False:
  File "F:\py\insta.py", line 45, in login
    if (self.SendRequest('accounts/login/', self.generateSignature(json.dumps(data)), True)):
  File "F:\py\insta.py", line 73, in generateSignature
    return 'ig_sig_key_version=' + self.SIG_KEY_VERSION + '&signed_body=' + hmac.new(self.IG_SIG_KEY.encode('utf-8'), data.encode('utf-8'), hashlib.sha256).hexdigest() + '.' + urllib.pathname2url(data)
  File "C:\Users\Amir\.windows-build-tools\python27\lib\nturl2path.py", line 60, in pathname2url
    raise IOError, error
IOError: Bad path: .........

i use python 2 and whats the problem?

**Comment by gonultasbu** [comment]
same issue persists, doesn't work

**Comment by dion-ricky** [comment]
i got the same issue

**Comment by xeagl3x** [comment]
I have the same issue. Has anyone been able to solve? It has to do with urllib.pathname2url. It is unable to handle the data object being passed in. I'm running on a windows 10 environment

**Comment by johnvalin** [comment]
urllib has been updated, it should now be urllib.request.pathname2url

https://stackoverflow.com/questions/30654772/python-3-4-2-urlib-no-attribute-pathname2url

**Comment by shashwata27** [comment]
@johnvalin but the project is using python2.7
 and if I change to `urllib.request.pathname2url` it says urllib doesn't have a attribute request
