### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by heyvoon** [ozkc/instagram-unfollowers#3]
```
linux@linux-box ~/Scripts/python/instagram-unfollowers $ python main.py 429570963
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from insta import Instagram
  File "/home/linux/Scripts/python/instagram-unfollowers/insta.py", line 4, in <module>
    import requests
ImportError: No module named requests
```

**Comment by heyvoon** [comment]
Fixed by using PIP2 instead of PIP
